export const DIRECTIONS = Object.freeze({
    TURN_RIGHT_X_DEGREES: `TURN_RIGHT_X_DEGREES`,
    TURN_LEFT_X_DEGREES: `TURN_LEFT_X_DEGREES`,
    TURN_LEFT: 'TURN_LEFT',
    TURN_RIGHT: 'TURN_RIGHT',
    FORWARD_X: `FORWARD_X`,
});

export const REVERTED_DIRECTIONS = Object.freeze({
    TURN_LEFT: 'TURN_RIGHT',
    TURN_RIGHT: 'TURN_LEFT',
});
